name: ci

on:
  pull_request:
    branches: '*'
  push:
    branches:
      - master
      - main
      - 'release-*'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        golang: ['1.23', '1.24']
        # currently, we cannot run non-x86_64 machines on Github Actions cloud env.
    runs-on: ${{ matrix.os }}-latest
    name: CI golang ${{ matrix.golang }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - name: Test
        run: go test -v ./fluent
        shell: bash
